### ISSUE TITLE
Socratic Seminar 11 Topics

### ISSUE THREAD

**Issue by vnprc** [TriangleBitDevs/TriangleBitDevs.github.io#1]
Please post here to add any topics you would like to discuss at the next socratic seminar.

#### Taro Skepticism
A critical look at the [scalability properties](https://bitcoinmagazine.com/technical/scaling-problem-for-lightning-labs-taro) of the Taro protocol if deployed on the bitcoin blockchain

#### Advances in Channel Jamming Research
The prolifically productive dream team Gleb Naumenko and Antoine Riard have released a series of research reports examining [channel jamming](https://bitcoinops.org/en/topics/channel-jamming-attacks/). Read the [lightning-dev post](https://lists.linuxfoundation.org/pipermail/lightning-dev/2022-August/003673.html) for a brief summary or dive into the [gitbook](https://jamming-dev.github.io/book/) and read the whole shebang.

#### Taproot Errwhere
Very exciting PR [enabling taproot by default](https://github.com/lightningnetwork/lnd/pull/6810) for sweeping funds, funding channels, and sending blobs to watch towers.

#### Coinpool
Gleb and Antoine propose [Coinpool](https://coinpool.dev/v0.1.pdf), a new shared UTXO ownership model. Coinpool requires three new OP codes to be soft forked into bitcoin script, so don’t hold your breath. It is recommended that you first grok [Eltoo](https://bitcoinops.org/en/topics/eltoo/) since coinpool builds upon the eltoo protocol to add new capabilities.

#### Coinjoin over nostr
alicexbt shared a [coinjoin over nostr](https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2022-August/020875.html) implementation to the bitcoin-dev mailing list. [Nostr](https://github.com/nostr-protocol/nostr) is a simple new decentralized social media protocol based on cryptographic keypairs.

#### Taproot address adoption
How can the addresses be added to a wallet? What is the difference between taproot and bech32? Does taproot save on costs? How much?
New website launched [When Taproot?](https://whentaproot.org/)

**Comment by vnprc** [comment]
New stuff that I think is extremely cool:

### Chaumian Mints
#### Fedimint launches on signet
This represents a big step towards a production ready codebase. https://twitter.com/EricSirion/status/1572329210727010307

#### Cashu
[Cashu](https://github.com/callebtc/cashu) is a Chaumian Ecash wallet and mint. It's written in python and has only lightning support, no on-chain transactions. It's like fedimint without a federation.

### Privacy
#### Spiral block explorer
[Spiral](https://btc.usespiral.com/) is a new Bitcoin block explorer that uses fully homomorphic encryption to guarantee the privacy of your balance lookups. Not to be confused with Jack Dorsey's bitcoin company of the same name. Who'd have thunk that the first big name collision would include none of the words "bit", "block", "chain", or "coin". ¯\_(ツ)_/¯

**Comment by jesseaam** [comment]
## Wasabi Wallet
[Wasabi Wallet](https://wasabiwallet.io) is an open-source bitcoin wallet on GitHub [here](https://github.com/zkSNACKs/WalletWasabi) with the goal of making bitcoin more fungible. When you buy bitcoin from an exchange, they are required to follow KYC and AML rules/laws and thus collect your personal information. This allows third party to run chain analysis on the Bitcoin blockchain and view every transaction you make. This effectively removes your financial privacy. Wasabi Wallet implements [coinjoins](https://en.bitcoin.it/wiki/CoinJoin) to decouple this meta data and give you back your privacy. 

`Privacy is your ability to selectively reveal yourself to the world.`

**Comment by vnprc** [comment]
### Onion Messages and Asynchronous Lightning Payments
[LDK](https://lightningdevkit.org/) developer [vallywal](twitter.com/vallywal) explains how onion messages not only unlock bolt12 offers and blinded routes, but the combination of onion messages and PTLCs [enable async payments](https://lightningdevkit.org/blog/onion-messages-demystified/) over lightning that don't lock up network liquidity. Really tho, the awesomest part of this blog post is all the 🔥 diagrams.

**Comment by vnprc** [comment]
### Bitcoin Core 24.0 Release Candidate Testing Guide
Bitcoin core developer [kouloumos](twitter.com/kouloumos) put together a [testing guide](https://github.com/bitcoin-core/bitcoin-devwiki/wiki/24.0-Release-Candidate-Testing-Guide) for the 24.0 release candidate. There's a lot of cool stuff in this release, check out his twitter [thread](https://twitter.com/kouloumos/status/1574483503655403524) to see the highlights in 280 char chunks.

**Comment by vnprc** [comment]
### Taro alpha release
[Lightning Labs](https://lightning.engineering/) has released the taro daemon alpha. Despite what the name might imply the taro daemon is not a little monster that steals your root vegetables, it is a tool to issue and transfer assets on bitcoin and lightning. Check out this [blog post](https://lightning.engineering/posts/2022-9-28-taro-launch/) for the English explanation or [the repo](https://github.com/lightninglabs/taro/) if you want to get technical.
