### ISSUE TITLE
Socratic Seminar 12 Topics

### ISSUE THREAD

**Issue by jesseaam** [TriangleBitDevs/TriangleBitDevs.github.io#2]
Please post here to add any topics you would like to discuss at the next socratic seminar.

#### Taro Skepticism

A critical look at the [scalability properties](https://bitcoinmagazine.com/technical/scaling-problem-for-lightning-labs-taro) of the Taro protocol if deployed on the bitcoin blockchain

#### Advances in Channel Jamming Research

The prolifically productive dream team Gleb Naumenko and Antoine Riard have released a series of research reports examining [channel jamming](https://bitcoinops.org/en/topics/channel-jamming-attacks/). Read the [lightning-dev post](https://lists.linuxfoundation.org/pipermail/lightning-dev/2022-August/003673.html) for a brief summary or dive into the [gitbook](https://jamming-dev.github.io/book/) and read the whole shebang.

#### Taproot Errwhere

Very exciting PR https://github.com/lightningnetwork/lnd/pull/6810 for sweeping funds, funding channels, and sending blobs to watch towers.

#### Coinpool

Gleb and Antoine propose [Coinpool](https://coinpool.dev/v0.1.pdf), a new shared UTXO ownership model. Coinpool requires three new OP codes to be soft forked into bitcoin script, so don’t hold your breath. It is recommended that you first grok [Eltoo](https://bitcoinops.org/en/topics/eltoo/) since coinpool builds upon the eltoo protocol to add new capabilities.

#### Taproot address adoption

How can the addresses be added to a wallet? What is the difference between taproot and bech32? Does taproot save on costs? How much?
New website launched [When Taproot?](https://whentaproot.org/)

**Comment by jesseaam** [comment]
## Border Wallets
[Border Wallets](https://www.borderwallets.com) are a new way to quickly and easily memorize Bitcoin seed phrases.

**Comment by vnprc** [comment]
### Lightning

#### CLN Channel Splicing Draft PR

Dustin Dettmer has opened a [draft PR](https://github.com/ElementsProject/lightning/pull/5675) to enable [channel splicing](https://bitcoinops.org/en/topics/splicing/) on CLN. There is a long list of TODO items to get this PR across the finish line but this feature represents a massive improvement to LN usability.

**Comment by jesseaam** [comment]
## News
CashApp fully integrates lightning ([ref](https://bitcoinmagazine.com/business/cash-app-enables-bitcoin-lightning-payments-for-40-million-users)).

**Comment by vnprc** [comment]
## Bitcoin Core
### [PR merged] wallet: fast rescan with BIP157 block filters for descriptor wallets
[PR #25957](https://github.com/bitcoin/bitcoin/pull/25957) enables fast wallet rescan using compact block filters, only for descriptor wallets.

**Comment by vnprc** [comment]
## Privacy

[ln-vortex](https://github.com/ln-vortex/ln-vortex) is a tool written in scala that allows coinjoin lightning channel opens. [Ben Carman](https://twitter.com/benthecarman) and [@deregs_](https://twitter.com/deregs_) just opened the first mainnet [vortex coinjoin](https://mempool.space/tx/5027541d328c2bab61e12c0db6df87f8a9f16dc10084042e4f4c962bdcbeb6fa).

**Comment by jesseaam** [comment]
### Clark Moody Bitcoin Dashboard

Found this cool dashboard to get a summary of the entire bitcoin ecosystem at a glance. https://bitcoin.clarkmoody.com/dashboard/
