### ISSUE TITLE
Freedom Tech Workshop 2 - June 2024

### ISSUE THREAD

**Issue by vnprc** [TriangleBitDevs/TriangleBitDevs.github.io#21]
# Welcome

Hello freedom fighters! This is where we'll organize the topics of discussion for our upcoming Freedom Tech Workshop.

Please use this issue to suggest topics that you'd like to see discussed at the meeting. To suggest a topic, simply add a new comment to this issue with the topic title as the comment's title.

As we work through organizing the topics, feel free to edit and update your comments as needed. This will help us keep everything organized and easy to follow.

To help get us started, here are some important fields of freedom technology:

- Social Media
- Privacy
- Self Hosting
- DID: Decentralized Identity
- File Hosting
- Protocol Design

Thank you for your contributions and we look forward to a great seminar!

**Comment by vnprc** [comment]
Suggested deep dive: Blossom decentralized file hosting protocol
introduction: https://njump.me/naddr1qqxkymr0wdek7mfdv3exjan9qgszv6q4uryjzr06xfxxew34wwc5hmjfmfpqn229d72gfegsdn2q3fgrqsqqqa28e4v8zy
github: https://github.com/hzrd149/blossom

**Comment by seanpk** [comment]
Is there are use for colored coins for app-specific uses/economies?
Here's an intro from BISQ: https://www.youtube.com/watch?v=xQTNigsrlO4
