### ISSUE TITLE
Socratic Seminar 31 - July 2024

### ISSUE THREAD

**Issue by vnprc** [TriangleBitDevs/TriangleBitDevs.github.io#23]
# Welcome

Hello Bitcoiners! This is where we'll organize the topics of discussion for our upcoming Socratic Seminar.

Please use this issue to suggest topics that you'd like to see discussed at the seminar. To suggest a topic, simply add a new comment to this issue with the topic title as the comment's title.

As we work through organizing the topics, feel free to edit and update your comments as needed. This will help us keep everything organized and easy to follow.

To help get us started, here are some main topics of discussion that we could consider:

- Bitcoin Core
- Lightning Network
- Scaling
- Privacy
- Media
- Miscellaneous
-
Remember, this is **Bitcoin only**, do not post about your favorite clown-coin.<br>
Thank you for your contributions and we look forward to a great seminar!

**Comment by vnprc** [comment]
joinstr v0.1.0 release notes
https://gitlab.com/invincible-privacy/joinstr/-/blob/main/doc/release-notes/plugin/release-notes-v0.1.0.md

**Comment by johnny9** [comment]
Bitcoin Core release 27.1
https://bitcoincore.org/en/releases/27.1/

**Comment by vnprc** [comment]
LND DoS vulnerability disclosure
https://morehouse.github.io/lightning/lnd-onion-bomb/

**Comment by vnprc** [comment]
### Ecash
GNU Taler
https://taler.net/en/features.html

Blinded Auth Tokens are happening
https://blog.mutinywallet.com/blinded-authentication/
https://one.google.com/about/vpn/howitworks

**Comment by vnprc** [comment]
Strike launches BOLT12 playground docker stack
https://strike.me/blog/bolt12-playground/

**Comment by vnprc** [comment]
Burak's at it again! Redefining an entire subdomain of bitcoin with an innovative new rollup design based on vTXOs.
https://brqgoo.medium.com/introducing-brollups-18ec4081f6e7

Recommended prerequisite reading:
https://bitcoinrollups.org/

**Comment by vnprc** [comment]
detailed technical writeup on silent payments
https://medium.com/@ottosch/how-silent-payments-work-41bea907d6b0

**Comment by vnprc** [comment]
Public disclosure of 10 security vulnerabilities that were fixed in bitcoin 0.21.0 and earlier.
https://github.com/bitcoin-core/bitcoincore.org/pull/1042

**Comment by vnprc** [comment]
[Vojtěch Strnad](https://x.com/vostrnad/status/1810022538933887280) explains all the easter eggs he included in this most complex bitcoin transaction ever(?).
https://stacker.news/items/600187

**Comment by vnprc** [comment]
Block's first ASIC customer
https://x.com/jack/status/1811033076241150247
