### ISSUE TITLE
TABConf 6 Socratic Session: Lightning Protocol Development

### ISSUE THREAD

**Issue by vnprc** [TriangleBitDevs/TriangleBitDevs.github.io#28]
# Welcome

Hello Bitcoiners! This is where we'll organize the topics of discussion for our upcoming Socratic Seminar.

Please use this issue to suggest topics that you'd like to see discussed at the seminar. To suggest a topic, simply add a new comment to this issue with the topic title as the comment's title.

As we work through organizing the topics, feel free to edit and update your comments as needed. This will help us keep everything organized and easy to follow.

**Comment by vnprc** [comment]
### Breez SDK adds support for Nodeless (Liquid) and Native (Greenlight) Implementations

The boys at Breez have done it again! The latest SDK refresh adds a 'nodeless' implementation that stores your balance on the Liquid sidechain. It uses a swap service to send and receive bitcoin or lightning, a model pioneered by Aqua Wallet. In addition, the Breez SDK offers a native lightning implementation built using the lightweight self-custodial Greenlight service for a pure lightning architecture that makes no compromises on the trust assumptions of bitcoin and lightning.

Check out the Blockstream [blog announcement](https://blog.liquid.net/breez-releases-nodeless-sdk-implementation-powered-by-liquid/), Breez [github](https://github.com/breez), [nodeless sdk docs](https://sdk-doc-liquid.breez.technology/), or [native sdk docs](https://sdk-doc-greenlight.breez.technology/) for more information.

**Comment by vnprc** [comment]
### BOLT12 Offers Merged

After four long years the BOLT12 Offers spec has been [merged](https://github.com/lightning/bolts/pull/798) into the BOLTs repo. Oh happy day! \o/

BOLT12 offers enable a static lightning invoice that works by communicating invoice parameters through the lightning network using onion messages to anonymously retrieve a BOLT11 invoice. It also uses blinded paths to conceal the endpoint of the lightning route, enabling private and trustless lightning payments. The static address represents a massive usability improvement over ephemeral and interactive BOLT11 invoices. Routing messages through the lightning network removes the need to incorporate a different network stack and thus the need to run a web server, which is approach taken by the LNURL protocol to achieve the same goals.

**Comment by vnprc** [comment]
https://delvingbitcoin.org/t/hybrid-jamming-mitigation-results-and-updates/1147

**Comment by vnprc** [comment]
https://github.com/lightningdevkit/rust-lightning/releases/tag/v0.0.124

**Comment by vnprc** [comment]
Not really sure what this means but it looks interesting. https://github.com/lightningnetwork/lnd/pull/8960/files#diff-d8ed3157089b4fb9b6e61d523fd956f2adfd223fdc76d000112bb8e2dab96e8e

**Comment by vnprc** [comment]
https://github.com/lightningdevkit/rust-lightning/releases/tag/v0.0.124

**Comment by vnprc** [comment]
LND gossip messages
https://github.com/lightningnetwork/lnd/pull/8044

**Comment by vnprc** [comment]
Eclair: Allow including routing hints when creating Bolt 11 invoice
https://github.com/ACINQ/eclair/pull/2909

**Comment by vnprc** [comment]
LN Summit 2024 Notes & Summary/Commentary
https://delvingbitcoin.org/t/ln-summit-2024-notes-summary-commentary/1198

**Comment by vnprc** [comment]
https://github.com/TABConf/6.tabconf.com/issues/148

**Comment by Randy808** [comment]
Spec for dual funding merged into BOLTs
https://github.com/lightning/bolts/pull/851

**Comment by Randy808** [comment]
Bitcoin Core 28 wallet integration guide
https://bitcoinops.org/en/bitcoin-core-28-wallet-integration-guide/

Discusses the impact of TRUC transactions on anchor outputs and the potential future deprecation of `update_fee` as well RBF pinning attacks
