### ISSUE TITLE
Socratic Seminar #15

### ISSUE THREAD

**Issue by vnprc** [TriangleBitDevs/TriangleBitDevs.github.io#5]
### [net_processing: the "version" handshake](https://github.com/brunoerg/bitcoin-core-notes/blob/main/general-notes/net_processing_version_handshake.md)

**Comment by jesseaam** [comment]
# Signing Device 
Secure Elements & Blind Oracles

### Introduction

* Private keys are the crucial element for owning bitcoin, and the adage "not your keys, not your coins" highlights the importance of keeping them safe.
* The majority of threats to private keys exist online, making hardware wallets a good solution for keeping them offline and safe from malware, spyware, and phishing scams.
* Hardware wallets can be vulnerable if they are physically obtained. For example through [Power glitching](https://www.ledger.com/academy/how-to-hack-a-hardware-wallet). This is done by rapidly and repeatedly cycling the power supply, causing the device to malfunction temporarily and allowing the hacker to extract the private keys during that momentary malfunction.
    * [Glitch the chip](https://youtube.com/clip/UgkxCL2dinn7n-7QoFTAgA-V73MDPBUSKGC-)
    * [Debug mode: access RAM](https://youtube.com/clip/UgkxOL_0SusA-xfI8TbOEcRtPkItB6IbIeex)

### Secure Elements in Hardware Wallets

* Secure elements are small, tamper-proof chips or microcontrollers that are typically found within hardware wallets. They are responsible for key material management, meaning they store, generate, and protect the private keys used to access and manage the user's bitcoin funds.
* Both ColdCard and Ledger use secure elements to protect the private keys in their hardware wallets.
* ColdCard's secure element is a Microchip PIC microcontroller and it uses a unique approach called "air-gapped" signing, which uses a separate device called the "MicroSD card writer" to transfer data between the ColdCard and the computer. This ensures that the private keys never come into contact with an online device, adding an extra layer of security.
* Ledger's secure element is a ST31H320 secure microcontroller and it uses a two-factor authentication, where the user must enter a pin code on the device to access the private key and sign transactions.

### Blind Oracle: A Different Approach

* Blockstream Jade uses a remote server, or "blind Oracle," to achieve similar security to a secure element without using one.
* The blind Oracle, when provided with the correct PIN, will give the user an AES 256-bit key to decrypt their wallet.
* If the wrong PIN is entered multiple times, the server will delete the key and the local encrypted material will be useless, forcing the user to start from their mnemonic recovery.
* This approach aims to achieve a level of security similar to that of a secure element, but with increased transparency and lower cost and hardware complexity.

### Conclusion

* Choosing a reputable and secure hardware wallet is crucial for protecting your bitcoin, and it's important to understand the potential vulnerabilities of the device.
* Secure elements and blind Oracles are two different ways to secure private keys and they both have their own advantages and disadvantages.
* Ultimately, it's important to research and understand the various options available and choose the one that best suits your needs and provides the highest level of security for your bitcoin.
* For further information, you can watch the video "What Is a Secure Element in a Hardware Wallet?" by Lawrence Nahum, Blockstream’s Chief Architect, that discusses the use of secure elements in hardware wallets and how Blockstream Jade uses a blind oracle-enforced PIN to achieve similar security with greater simplicity and transparency.

**Comment by vnprc** [comment]
### Cashabi
[Cashabi](https://lontivero.github.io/Wiki/html/cashabi.html) is a new ecash proposal based on WabiSabi’s Keyed-Verification Anonymous Credentials and Nostr E2E encryption messages.

### Ordinal Inscriptions: NFTs on bitcoin
[ordinals.com](http://ordinals.com/) is a site to browse ordinal inscriptions, a new NFT scheme built on bitcoin by SF BitDevs host [@rodarmor](https://twitter.com/rodarmor). Ordinals is a scheme to number and track every satoshi based on its issuance date. [Inscriptions](https://docs.ordinals.com/guides/inscriptions.html) are a scheme to associate on-chain metadata to a single satoshi ordinal. The data is stored in the tx witness script, leading to heated debates about whether inscriptions are a good or bad thing. The cool part, though, is that in a permissionless system nobody can stop you from minting NFTs as long as you pay the network fee.

**Comment by vnprc** [comment]
Bitcoin technical search
https://bitcoinsearch.xyz/

Mempool block audit view
https://mempool.space/docs/faq#what-is-block-health
